version: "3"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pern_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  db_manager:
    container_name: db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db/db_manager:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - db
      - app
    restart: unless-stopped
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - "8000:3000"
    networks:
      - app
    restart: unless-stopped
networks:
  app:
  db:
    driver: bridge
